- name: Configure Pentest Workstation
  hosts: pentest
  become: true
  gather_facts: true

  vars_files:
    - config.yml

  tasks:
    - name: Install common packages
      include_role: 
        name: common
      vars:
        pyenv: "yes"
        rust: "yes"
        zshell: "yes"

    - name: Install desktop packages
      include_role: 
        name: desktop
      vars:
        brave: "yes"

    - name: Install golang
      include_role:
        name: golang
        
    - name: Install pentesting packages
      include_role: 
        name: pentest

    - name: Install PIPX Packages
      community.general.pipx:
        name: "{{ item }}"
        state: present
      loop:
        - asciinema
        - fierce
        - dnsrecon
        - arjun
