- name: Configure Workstation
  hosts: debwork
  become: true
  gather_facts: true

  vars_files:
    - config/config.yml

  tasks:
    - name: Install common packages
      include_role: 
        name: common
      vars:
        pyenv: "yes"
        rust: "yes"
        ipsec: "no"
        zshell: "yes"

    - name: Install desktop packages
      include_role: 
        name: desktop
      vars:
        brave: "no"
        signal: "no"

    - name: Install other packages 
      apt:
        pkg:
          - docker.io
          - tcpdump
          - libpcap0.8-dev

    - name: Add user to several groups using a loop
      command: usermod -aG "{{ item }}" {{ ansible_user }}
      with_items:
        - input
        - disk
      delegate_to: localhost

    - name: Setup git global user
      become_user: "{{ ansible_user }}"
      community.general.git_config:
        name: user.name
        value: "{{ git_user_name }}"
        scope: global        

    - name: Setup git global email
      become_user: "{{ ansible_user }}"
      community.general.git_config:
        name: user.email
        value: "{{ git_email }}"
        scope: global
