- name: Configure Pentest Workstation
  hosts: pentest
  become: true
  gather_facts: true

  vars:
    distribution: ansible_facts["distribution"]
    msf_install_directory: "/opt/metasploit-framework"

  tasks:
    - name: Install common packages
      include_role: 
        name: common
      vars:
        pyenv: "yes"

    - name: Install desktop packages
      include_role: 
        name: desktop
      vars:
        brave: "yes"

    - name: Install golang
      include_role: 
        name: gantsign.golang
      vars:
        golang_gopath: '$HOME/go'

    - name: Setup Bash Environment
      lineinfile:
        path: "~/.bashrc"
        line: "{{ item }}"
        insertafter: EOF
        create: yes
      loop:
        - 'export GOROOT=/usr/lib/go'
        - 'export GOPATH=$HOME/go'
        - 'export PATH=$GOPATH/bin:$GOROOT/bin:$PATH'
      when: ansible_env.SHELL == "/bin/bash"
      become_user: "{{ ansible_user }}"

    - name: Setup Zsh Environment
      lineinfile:
        path: "~/.zshrc"
        line: "{{ item }}"
        insertafter: EOF
        create: yes
      loop:
        - 'export GOROOT=/usr/lib/go'
        - 'export GOPATH=$HOME/go'
        - 'export PATH=$GOPATH/bin:$GOROOT/bin:$PATH'
      when: ansible_env.SHELL == "/bin/zsh"
      become_user: "{{ ansible_user }}"

    - name: Install pentesting packages
      include_role: 
        name: pentest
