- name: Configure Workstation
  hosts: uwork
  become: true
  gather_facts: true

  vars_files:
    - /config/config.yml

  tasks:
    - name: Install common packages
      include_role: 
        name: common
      vars:
        pyenv: "yes"
        rust: "yes"
        ipsec: "yes"
        zshell: "yes"

    - name: Install desktop packages
      include_role: 
        name: desktop
      vars:
        brave: "yes"

    - name: Install other packages 
      apt:
        pkg:
          - docker.io
          - tcpdump
          - libpcap0.8-dev

    # - name: Install Rust packages
    #   # The community cargo command isn't working here
    #   # I think because it isn't playing attention
    #   # to the "become_user".
    #   become_user: "{{ ansible_user }}"
    #   ansible.builtin.command:
    #     cmd: "~/.cargo/bin/cargo install {{ item }}"
    #   loop:
    #     # nushell takes a long time to install. You
    #     # probably want to comment this out unless
    #     # you really want to use it.
    #     #- nu
    #     - base64

    - name: Setup git global user
      become_user: "{{ ansible_user }}"
      community.general.git_config:
        name: user.name
        value: "{{ git_user_name }}"
        scope: global        

    - name: Setup git global email
      become_user: "{{ ansible_user }}"
      community.general.git_config:
        name: user.email
        value: "{{ git_email }}"
        scope: global
