- name: Configure Workstation
  hosts: uwork
  become: true
  gather_facts: true

  vars_files:
    - config.yml

  tasks:
    - name: Install common packages
      include_role: 
        name: common
      vars:
        pyenv: "yes"
        rust: "yes"
        ipsec: "yes"

    - name: Install desktop packages
      include_role: 
        name: desktop
      vars:
        brave: "yes"

    - name: Install 'nushell'
      community.general.cargo:
        name: 'nu' 
      become_user: "{{ ansible_user }}"

    - name: Setup git global user
      community.general.git_config:
        name: user.name
        value: "{{ git_user_name }}"
        scope: global        
      become_user: "{{ ansible_user }}"

    - name: Setup git global email
      community.general.git_config:
        name: user.email
        value: "{{ git_email }}"
        scope: global
      become_user: "{{ ansible_user }}"