ipsec_subnet: "10.11.13.0/24"
ipsec_sourceip: "10.11.13.23"
git_user_name: itsame
git_email: mario@bowzer.castle.com
msf_install_directory: "/opt/metasploit-framework"
burpsuite_version: "2023.11.1.5"
hackthebox_config: "./files/htb.ovpn"