# Install the Brave Browser. You'll still have to run and configure it.
- name: Add Brave Browser GPG Key
  ansible.builtin.get_url:
    url: "https://brave-browser-apt-release.s3.brave.com/brave-core.asc"
    dest: /etc/apt/trusted.gpg.d/brave-core.asc
    mode: '0644'
    force: true

- name: Add Brave Browser repository
  apt_repository:
    repo: deb [arch=amd64] https://brave-browser-apt-release.s3.brave.com/ stable main
    state: present

- name: Update apt package cache
  apt:
    update_cache: "yes"

- name: Install Brave Browser
  apt:
    name: brave-browser
    state: present

