# Installs desktop apps
- name: Install desktop packages for Debian/Ubuntu
  apt:
    pkg:
      - nextcloud-desktop
      - cherrytree
      - copyq
      - terminator
      - flatpak
      - gnome-software-plugin-flatpak
    state: present

# TODO: might make this a default later.
# flatpak install flathub md.obsidian.Obsidian

- name: Flathub repository
  command: flatpak remote-add --if-not-exists flathub https://dl.flathub.org/repo/flathub.flatpakrepo

- name: Update alternatives for x-terminal-emulator
  command: update-alternatives --set x-terminal-emulator /usr/bin/terminator

- include_tasks: "{{ role_path }}/tasks/pip-packages.yml"
- include_tasks: "{{ role_path }}/tasks/keepassxc.yml"
- include_tasks: "{{ role_path }}/tasks/codium.yml"

- name: Install Brave if "brave" is "yes".
  include_tasks: "{{ role_path }}/tasks/brave.yml"
  when: "'yes' | lower in brave | default('') | lower"

- name: Install Signal if "signal" is "yes".
  include_tasks: "{{ role_path }}/tasks/signal.yml"
  when: "'yes' | lower in signal | default('') | lower"

