# Installs desktop apps
- name: Install desktop packages for Debian/Ubuntu
  apt:
    pkg:
      - nextcloud-desktop
      - cherrytree
      - copyq
      - terminator
    state: present

- name: Update alternatives for x-terminal-emulator
  command: update-alternatives --set x-terminal-emulator /usr/bin/terminator

- include_tasks: "{{ role_path }}/tasks/pip-packages.yml"
- include_tasks: "{{ role_path }}/tasks/keepassxc.yml"
- include_tasks: "{{ role_path }}/tasks/codium.yml"

- name: Install Brave if "brave" is "yes".
  include_tasks: "{{ role_path }}/tasks/brave.yml"
  when: "'yes' | lower in brave | default('') | lower"

