- name: Add Signal GPG Key
  ansible.builtin.get_url:
    url: "https://updates.signal.org/desktop/apt/keys.asc"
    dest: /etc/apt/trusted.gpg.d/signal-keys.asc
    mode: '0644'
    force: true

- name: Add Signal repository
  apt_repository:
    repo: deb [arch=amd64 signed-by=/usr/share/keyrings/signal-desktop-keyring.gpg] https://updates.signal.org/desktop/apt xenial main
    state: present

- name: Update apt package cache
  apt:
    update_cache: "yes"

- name: Install Signal
  apt:
    name: signal-desktop
    state: present
