# This is still in testing. Might break or even come pre-broken.

- name: Import Signal Messenger GPG key
  command: >
    wget -O- https://updates.signal.org/desktop/apt/keys.asc | gpg --dearmor > /usr/share/keyrings/signal-desktop-keyring.gpg
  args:
    creates: "/usr/share/keyrings/signal-desktop-keyring.gpg"
  delegate_to: localhost

- name: Add Signal repository
  apt_repository:
    repo: deb [arch=amd64 signed-by=/usr/share/keyrings/signal-desktop-keyring.gpg] https://updates.signal.org/desktop/apt xenial main
    state: present

- name: Update package lists
  apt:
    update_cache: yes
    cache_valid_time: 3600 # Cache valid for 1 hour

- name: Install Signal Messenger
  apt:
    name: "signal-desktop"
    state: present
    update_cache: yes