
# Installs the libreswan package and configures it using the files in the
# assets/ directory. 
- name: Install libreswan
  apt:
    name: libreswan
    state: present

- name: Copy ipsec.conf
  copy:
    src: "~/.config/ipsec.conf"
    dest: /etc/ipsec.conf

# There are 2 instances of leftsubnet and leftsourceip in the config file
# but I could not craft the spell required to get lininfile to replace
# them both. So the work around is to run the command twice with two
# different keys, then replace both the key and value. There has to be 
# a better way.
- name: Configure leftsubnet in ipsec.conf
  lineinfile:
    path: /etc/ipsec.conf
    regexp: "^(#?\\s*leftsubnet1=).*"
    line: "        leftsubnet={{ ipsec_subnet }}"
    state: present

- name: Configure leftsubnet in ipsec.conf
  lineinfile:
    path: /etc/ipsec.conf
    regexp: "^(#?\\s*leftsubnet2=).*"
    line: "        leftsubnet={{ ipsec_subnet }}"
    state: present

- name: Configure leftsourceip in ipsec.conf
  lineinfile:
      path: /etc/ipsec.conf
      regexp: "^(#?\\s*leftsourceip1=).*"
      line: "        leftsourceip={{ ipsec_sourceip }}"

- name: Configure leftsourceip in ipsec.conf
  lineinfile:
      path: /etc/ipsec.conf
      regexp: "^(#?\\s*leftsourceip2=).*"
      line: "        leftsourceip={{ ipsec_sourceip }}"

- name: Ensure ipsec service is enabled
  systemd:
    name: ipsec
    enabled: yes
  ignore_errors: yes

- name: restart ipsec
  systemd:
    name: ipsec
    state: restarted