# Installs common packages
- name: Install common packages for Debian/Ubuntu
  apt:
    pkg:
    - build-essential
    - git
    - curl
    - terminator
    - pip
    - wireshark
    - openvpn
    - pkg-config 
    - libssl-dev
    state: present
    update_cache: true

- name: Update alternatives for x-terminal-emulator
  command: update-alternatives --set x-terminal-emulator /usr/bin/terminator

- include_tasks: "{{ role_path }}/tasks/resolved.yml"

- name: Install pyenv if "pyenv" is defined.
  include_tasks: "{{ role_path }}/tasks/pyenv.yml"
  when: "'yes' | lower in pyenv | default('') | lower"

- name: Install rust if "rust" is defined.
  include_tasks: "{{ role_path }}/tasks/rust.yml"
  when: "'yes' | lower in rust | default('') | lower"
