- name: Update apt package cache
  apt:
    update_cache: "yes"

# Installs common packages
- name: Install common packages for Debian/Ubuntu
  apt:
    pkg:
    - build-essential
    - git-all
    - curl
    - pip
    - wireshark
    - openvpn
    - net-tools
    - cowsay
    - fortune
    - calendar
    - bastet
    - rig
    - autojump
    - fzf
    state: present
    update_cache: true

- name: Install Zshell if "zshell" is "yes".
  include_tasks: "{{ role_path }}/tasks/zshell.yml"
  when: "'yes' | lower in zshell | default('') | lower"

- name: Update PATH (bashrc)
  lineinfile:
    path: "~/.bashrc"
    line: "{{ item }}"
    insertafter: EOF
    create: yes
  loop:
    - 'export PATH="~/.local/bin:$PATH"'
  when: ansible_env.SHELL == "/bin/bash"
  become_user: "{{ ansible_user }}"
  notify:
    - reload bashrc

- name: Update PATH (zsh)
  lineinfile:
    path: "~/.zshrc"
    line: "{{ item }}"
    insertafter: EOF
    create: yes
  loop:
    - 'export PATH="~/.local/bin:$PATH"'
  when: ansible_env.SHELL == "/bin/zsh"
  become_user: "{{ ansible_user }}"
  notify:
    - reload zshrc

- name: Install IPSec if "ipsec" is "yes".
  include_tasks: "{{ role_path }}/tasks/ipsec.yml"
  when: "'yes' | lower in ipsec | default('') | lower"

#- include_tasks: "{{ role_path }}/tasks/resolved.yml"

- name: Install pyenv if "pyenv" is defined.
  include_tasks: "{{ role_path }}/tasks/pyenv.yml"
  when: "'yes' | lower in pyenv | default('') | lower"

- name: Install rust if "rust" is defined.
  include_tasks: "{{ role_path }}/tasks/rust.yml"
  when: "'yes' | lower in rust | default('') | lower"
