# Installs common packages
- name: Install common packages for Debian/Ubuntu
  apt:
    pkg:
    - build-essential
    - git
    - curl
    - pip
    - wireshark
    - openvpn
    - pkg-config 
    - libssl-dev
    state: present
    update_cache: true

- name: Install IPSec if "ipsec" is "yes".
  include_tasks: "{{ role_path }}/tasks/ipsec.yml"
  vars:
    ipsec_subnet: ipsec_subnet
    ipsec_sourceip: ipsec_sourceip
  when: "'yes' | lower in ipsec | default('') | lower"

- include_tasks: "{{ role_path }}/tasks/resolved.yml"

- name: Install pyenv if "pyenv" is defined.
  include_tasks: "{{ role_path }}/tasks/pyenv.yml"
  when: "'yes' | lower in pyenv | default('') | lower"

- name: Install rust if "rust" is defined.
  include_tasks: "{{ role_path }}/tasks/rust.yml"
  when: "'yes' | lower in rust | default('') | lower"
