- name: Install required dependencies for pyenv
  apt:
    pkg:
      - git
      - curl
      - zlib1g-dev
      - libssl-dev
      - libreadline-dev
      - libbz2-dev
      - libsqlite3-dev
      - build-essential
    state: present
    
- name: Clone pyenv repository
  git:
    repo: "https://github.com/pyenv/pyenv.git"
    dest: "~/.pyenv"
    update: yes
  become_user: "{{ ansible_user }}"

- name: Add pyenv to shell profile
  lineinfile:
    path: "~/.bashrc"
    line: "{{ item }}"
    insertafter: EOF
    create: yes
  loop:
    - 'export PYENV_ROOT="$HOME/.pyenv"'
    - '[[ -d $PYENV_ROOT/bin ]] && export PATH="$PYENV_ROOT/bin:$PATH"'
    - 'eval "$(pyenv init -)"'
    - 'eval "$(pyenv virtualenv-init -)"'
  when: ansible_env.SHELL == "/bin/bash"
  become_user: "{{ ansible_user }}"

- name: Add pyenv to shell profile for zsh
  lineinfile:
    path: "~/.zshrc"
    line: "{{ item }}"
    insertafter: EOF
    create: yes
  loop:
    - 'export PYENV_ROOT="$HOME/.pyenv"'
    - '[[ -d $PYENV_ROOT/bin ]] && export PATH="$PYENV_ROOT/bin:$PATH"'
    - 'eval "$(pyenv init -)"'
    - 'eval "$(pyenv virtualenv-init -)"'
  when: ansible_env.SHELL == "/bin/zsh"
  become_user: "{{ ansible_user }}"

- name: Clone pyenv-virtualenv plugin
  git:
    repo: https://github.com/pyenv/pyenv-virtualenv.git
    dest: "~/.pyenv/plugins/pyenv-virtualenv"
  when: "'plugins/pyenv-virtualenv' not in ('~/.pyenv/plugins') | list"
  become_user: "{{ ansible_user }}"
