- name: Download and run Rust installation script
  shell: curl --proto '=https' --tlsv1.3 -sSf https://sh.rustup.rs | sh -s -- -y
  when: "'~/.cargo/bin/cargo' is not file"
  become_user: "{{ ansible_user }}"

