- name: Check for Golang package
  stat:
    path: "/tmp/golang.tar.gz"
  register: golang_package
  become_user: "{{ ansible_user }}"

- name: Download Golang if necessary
  get_url:
    url: "https://go.dev/dl/go1.21.6.linux-amd64.tar.gz"
    dest: "/tmp/golang.tar.gz"
    mode: "0755"  # Set the appropriate permissions
  when: not golang_package.stat.exists
  become_user: "{{ ansible_user }}"

- name: Install Golang
  shell: "rm -rf /usr/local/go && tar -C /usr/local -xzf /tmp/golang.tar.gz"

- name: Setup Bash Environment
  lineinfile:
    path: "~/.bashrc"
    line: "{{ item }}"
    insertafter: EOF
    create: yes
  loop:
    - 'export GOROOT=/usr/local/go'
    - 'export GOPATH=$HOME/go'
    - 'export PATH=$GOPATH/bin:$GOROOT/bin:$PATH'
  when: ansible_env.SHELL == "/bin/bash"
  become_user: "{{ ansible_user }}"

- name: Setup Zsh Environment
  lineinfile:
    path: "~/.zshrc"
    line: "{{ item }}"
    insertafter: EOF
    create: yes
  loop:
    - 'export GOROOT=/usr/local/go'
    - 'export GOPATH=$HOME/go'
    - 'export PATH=$GOPATH/bin:$GOROOT/bin:$PATH'
  when: ansible_env.SHELL == "/bin/zsh"
  become_user: "{{ ansible_user }}"

