- name: Check for Burpsuite Installer
  stat:
    path: "~/Downloads/burbsuite-{{ burpsuite_edition }}-{{ burpsuite_version }}.sh"
  register: burbsuite_script
  become_user: "{{ ansible_user }}"

- name: Download the Burpsuite installer if needed
  get_url:
    url: "https://portswigger-cdn.net/burp/releases/download?product={{ burpsuite_edition }}&version={{ burpsuite_version }}&type=Linux"
    dest: "~/Downloads/burbsuite-{{ burpsuite_edition }}-{{ burpsuite_version }}.sh"
    mode: "0755"  # Set the appropriate permissions
  when: not burbsuite_script.stat.exists
  become_user: "{{ ansible_user }}"

- name: Install Burpsuite
  shell: "~/Downloads/burbsuite-{{ burpsuite_edition }}-{{ burpsuite_version }}.sh -q"
  become_user: "{{ ansible_user }}"
