- name: Load GitHub repo list
  set_fact:
    git_repositories: "{{ lookup('file', 'files/git_repositories.json') | from_json }}"

- name: Clone GitHub repositories
  git:
    repo: "{{ item.repo }}"
    dest: "{{ item.dest }}"
    version: "{{ item.version | default('master') }}"
    force: yes
  loop: "{{ git_repositories }}"

- name: Create symbolic links
  file:
    src: "{{ item.link_src }}"
    dest: "{{ item.link_dest }}"
    state: link
  when: item.link_src is defined and item.link_src != ""
  loop: "{{ git_repositories }}"

- name: Install IMPacket
  pip:
    requirements: /opt/impacket.git/requirements.txt
    state: present