- name: Clone GitHub repositories
  git:
    repo: "{{ item.repo }}"
    dest: "{{ item.dest }}"
    version: "{{ item.version | default('master') }}"
    force: yes
  loop:
    - { repo: "https://github.com/00xBAD/kali-wordlists.git", dest: "/usr/share/wordlists" }
    - { repo: "https://github.com/AonCyberLabs/Windows-Exploit-Suggester", dest: "/opt/Windows-Exploit-Suggester" }
    - { repo: "https://github.com/bitsadmin/wesng", dest: "/opt/wesng" }
    - { repo: "https://github.com/carlospolop/PEASS-ng", dest: "/opt/PEASS-ng" }
    - { repo: "https://github.com/carlospolop/privilege-escalation-awesome-scripts-suite", dest: "/opt/privilege-escalation-awesome-scripts-suite" }
    - { repo: "https://github.com/Cillian-Collins/dirscraper", dest: "/opt/dirscraper" }
    - { repo: "https://github.com/CiscoCXSecurity/enum4linux.git", dest: "/opt/enum4linux.git" }
    - { repo: "https://github.com/danielmiessler/SecLists.git", dest: "/usr/share/seclists" }
    - { repo: "https://github.com/darkoperator/dnsrecon", dest: "/opt/dnsrecon" }
    - { repo: "https://github.com/dirkjanm/krbrelayx", dest: "/opt/krbrelayx" }
    - { repo: "https://github.com/fox-it/mitm6", dest: "/opt/mitm6" }
    - { repo: "https://github.com/infodox/python-pty-shells.git", dest: "/opt/python-pty-shells.git" }
    - { repo: "https://github.com/lanjelot/patator.git", dest: "/opt/patator.git" }
    - { repo: "https://github.com/lgandx/Responder", dest: "/opt/Responder" }
    - { repo: "https://github.com/liamg/traitor.git", dest: "/opt/traitor.git", version: "main" }
    - { repo: "https://github.com/maurosoria/dirsearch", dest: "/opt/dirsearch" }
    - { repo: "https://github.com/mzet-/linux-exploit-suggester", dest: "/opt/linux-exploit-suggester" }
    - { repo: "https://github.com/OJ/gobuster.git", dest: "/opt/gobuster.git" }
    - { repo: "https://github.com/payloadbox/xss-payload-list", dest: "/opt/xss-payload-list" }
    - { repo: "https://github.com/phra/PEzor", dest: "/opt/PEzor" }
    - { repo: "https://github.com/rebootuser/LinEnum", dest: "/opt/LinEnum" }
    - { repo: "https://github.com/SecureAuthCorp/impacket.git", dest: "/opt/impacket.git" }
    - { repo: "https://github.com/sleventyeleven/linuxprivchecker", dest: "/opt/linuxprivchecker" }
    - { repo: "https://github.com/sqlmapproject/sqlmap.git", dest: "/opt/sqlmap.git" }
    - { repo: "https://github.com/swisskyrepo/PayloadsAllTheThings", dest: "/opt/PayloadsAllTheThings" }
    - { repo: "https://github.com/Tib3rius/AutoRecon.git", dest: "/opt/AutoRecon.git", version: "main" }
    - { repo: "https://github.com/tmux-plugins/tmux-logging", dest: "/opt/tmux-logging" }
    - { repo: "https://gitlab.com/exploit-database/exploitdb.git", dest: "/opt/exploitdb", version: "main" }

- name: Create symbolic links
  file:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    state: link
  loop:
    - { src: "/opt/enum4linux.git/enum4linux.pl", dest: "/usr/local/bin/enum4linux" }
    - { src: "/opt/exploitdb/searchsploit", dest: "/usr/local/bin/searchsploit" }
    - { src: "/opt/sqlmap.git/sqlmap.py", dest: "/usr/local/bin/sqlmap" }

- name: Install IMPacket
  pip:
    requirements: /opt/impacket.git/requirements.txt
    state: present