- name: Load GitHub repo list
  set_fact:
    git_repositories: "{{ lookup('file', 'files/git_repositories.json') | from_json }}"

- name: Clone GitHub repositories
  ansible.builtin.git:
    repo: "{{ item.repo }}"
    dest: "{{ item.dest }}"
    version: "{{ item.version | default('master') }}"
    force: yes
  loop: "{{ git_repositories }}"

- name: Create symbolic links
  file:
    src: "{{ item.link_src }}"
    dest: "{{ item.link_dest }}"
    state: link
  when: item.link_src is defined and item.link_src != ""
  loop: "{{ git_repositories }}"

- name: Complete oscanner Install
  copy:
    src: files/oscanner
    dest: /usr/local/bin/oscanner
    mode: "755"
    
- name: Set file permissions
  file:
    path: "{{ item.link_dest }}"
    mode: "{{ item.mode }}"
  when: (item.link_dest is defined and item.link_dest != "") and (item.mode is defined and item.mode != "")
  loop: "{{ git_repositories }}"

- name: Install Python packages from requirements file
  pip:
    requirements: "{{ item.dest }}/requirements.txt"
  when: (item.python_requirements is defined and item.python_requirements != "")
  loop: "{{ git_repositories }}"
  become_user: "{{ ansible_user }}"

- name: Install IMPacket
  pip:
    requirements: /opt/impacket.git/requirements.txt
    state: present

- name: Build and copy Traitor
  command: "make"
  args:
    chdir: "/opt/traitor.git"
