- name: Install Golang packages
  ansible.builtin.command:
    cmd: "/usr/local/go/bin/go install {{ item }}"
  loop:
    - github.com/dwisiswant0/hinject@latest
    - github.com/ffuf/ffuf@latest
    - github.com/OJ/gobuster/v3@latest
    - github.com/hahwul/dalfox@latest
    - github.com/hakluke/hakrawler@latest
    - github.com/lc/gau@latest
    - github.com/tomnomnom/assetfinder@latest
    - github.com/tomnomnom/httprobe@latest
  become_user: "{{ ansible_user }}"

- name: Update PATH (bashrc)
  lineinfile:
    path: "~/.bashrc"
    line: "{{ item }}"
    insertafter: EOF
    create: yes
  loop:
    - 'export PATH="~/go/bin:$PATH"'
  become_user: "{{ ansible_user }}"
  notify:
    - reload bashrc

- name: Update PATH (zsh)
  lineinfile:
    path: "~/.zshrc"
    line: "{{ item }}"
    insertafter: EOF
    create: yes
  loop:
    - 'export PATH="~/go/bin:$PATH"'
  become_user: "{{ ansible_user }}"
  notify:
    - reload zshrc
