- name: Install Golang packages
  ansible.builtin.command:
    cmd: "/usr/lib/go/bin/go install {{ item }}"
  loop:
    - github.com/tomnomnom/assetfinder@latest
    - github.com/tomnomnom/httprobe@latest
    - github.com/hakluke/hakrawler@latest
    - github.com/ffuf/ffuf@latest
    - github.com/dwisiswant0/hinject@latest
    - github.com/lc/gau@latest
    - github.com/hakluke/hakrawler@latest
    - github.com/hahwul/dalfox@latest
    - github.com/tomnomnom/httprobe@latest
