- name: restart systemd-resolved
  systemd:
    name: systemd-resolved
    state: restarted

- name: reload bashrc
  command: "source $HOME/.bashrc"

- name: reload zshrc
  command: "source $HOME/.zshrc"